[project]
name = "MACRO"
version = "0.12.4"
requires-python = ">= 3.10.0"
description = "This is the code for a prototype demo Mars Autonomous Cargo Rover Operations (MACRO)"
readme = "README.md"
dependencies = ["numpy"]
